Create 2-dps_1.md
FLBadoras/wiki pull request #100
Opened 2024-04-11 20:15 UTC by RobZenFL

---

### Related Issues

Closes #XXXX

### Reviewer's checklist

- [ ] ... Wurde eine gewisse Code-Qualität eingehalten?
- [ ] ... Stimmen die veränderten oder neu hinzugefügten Informationen?
- [ ] ... Wurden die Veränderungen getestet?

2024-04-12 15:14 UTC, motrellin requested changes

2024-04-12 15:14 UTC, motrellin commented on _team_members/2-dps_1.md
> +  - "Eventdurchführung"
```suggestion
position: Event-Organisation
```
Ich würde das aus zwei Gründen abändern:
1. Event-Organisation (alt. Event-Planung o.Ä.) passt besser zu den bisherigen Positionsbezeichnungen.
2. Wahrscheinlich typische Event-Aufgaben nochmal extra als Verantwortlichkeiten aufzuführen, erscheint mir redundant. Das ist irgendwie so, als ob man bei Support aufführen würde, dass sie verantwortlich für Discord-Support und Regelwerkdurchsetzung sind.

2024-04-13 14:05 UTC, RobZenFL commented
Ja, aber wenn du jetzt alle Positionen einmenscheln willst (SupportER), klingt das doofer. Und ist halt allgemein auch sehr sperrig. Glaub das braucht man nicht unnötig verkomplizieren.

2024-04-13 15:08 UTC, motrellin commented
> Ja, aber wenn du jetzt alle Positionen einmenscheln willst (SupportER), klingt das doofer. Und ist halt allgemein auch sehr sperrig. Glaub das braucht man nicht unnötig verkomplizieren.

Der aktuelle Trend sind anzahllose Bezeichnungen ("Heldchen ist Teil der Moderation"). Dieses Einmenscheln ist hier eigentlich nicht Thema.

Ein einheitliches Benennungssystem zeigt, dass sich da Gedanken gemacht wurden, weshalb es sinnvoll ist, dies einheitlich zu halten. Ob jetzt anzahllos oder eingemenschelt, ist mir persönlich egal. "Event" passt gerade zu beidem nicht.

2024-04-13 15:11 UTC, RobZenFL commented
Kann mit der Antwort wenig anfangen. Bleibe dabei, dass mir das unnötig erscheint.

Und Event passt in meiner Wahrnehmung besser zu "Support" und "Moderation", als "Event-Organisator".

2024-04-13 15:14 UTC, RobZenFL commented
Was rein garnichts an meiner Aussage ändert

2024-04-13 15:35 UTC, motrellin commented
Updated @RobZenFL

2024-04-13 15:35 UTC, motrellin approved these changes

2024-04-13 15:41 UTC, merged