[SYS] drinks -> fooddrinks
FLBadoras/wiki pull request #103
Opened 2024-04-12 21:01 UTC by motrellin

Information on food is now added. As drinks as well as foods need receipts, they are associated to each other and can be combined in on system.

---

### Related Issues

Closes #XXXX

### Reviewer's checklist

- [ ] ... Wurde eine gewisse Code-Qualität eingehalten?
- [ ] ... Stimmen die veränderten oder neu hinzugefügten Informationen?
- [ ] ... Wurden die Veränderungen getestet?

2024-04-12 21:53 UTC, RobZenFL requested changes

2024-04-12 21:53 UTC, RobZenFL commented on _systems/fooddrinks.md
> +Hast du Rezepte erfolreich erlernt hast, kannst du sie jederzeit per
Wichtig: Nur von NPC erlernte Rezepte erscheinen im /info-Rezeptebuch. Sollte man noch klarstellen!

2024-04-12 21:53 UTC, RobZenFL commented on _systems/fooddrinks.md
> +Hungrig? Die Herstellung von Speisen ist möglich, wenn auch etwas kompliziert
Ach, kompliziert ist es doch garnicht :D Sagt ja auch der schlaue Rzett!

2024-04-12 21:53 UTC, RobZenFL commented on _systems/fooddrinks.md
> +fast 400 Rezepte zur Verfügung!
"über 300"

2024-04-13 15:12 UTC, motrellin commented on _systems/fooddrinks.md
> +fast 400 Rezepte zur Verfügung!
done

2024-04-13 15:12 UTC, motrellin commented on _systems/fooddrinks.md
> +Hast du Rezepte erfolreich erlernt hast, kannst du sie jederzeit per
done

2024-04-13 15:37 UTC, RobZenFL approved these changes

2024-04-13 15:39 UTC, merged