Create helfer.md
FLBadoras/wiki pull request #109
Opened 2024-04-20 14:29 UTC by Ru8ior

---

### Related Issues

Closes #XXXX

### Reviewer's checklist

- [ ] ... Wurde eine gewisse Code-Qualität eingehalten?
- [ ] ... Stimmen die veränderten oder neu hinzugefügten Informationen?
- [ ] ... Wurden die Veränderungen getestet?

2024-04-20 16:05 UTC, motrellin commented
Hab mal helfer.md in support.md integriert nach Absprache auf Discord.

2024-04-20 16:06 UTC, motrellin approved these changes

2024-04-20 16:26 UTC, motrellin approved these changes

2024-04-20 18:26 UTC, RobZenFL requested changes
Würde anregen die Helfer nicht in die Teamliste aufzunehmen. Wir wollten die ja explizit nicht als Teamler haben + ist es so weniger Wartungsaufwand für uns, wenn da Personen auf dem Posten variieren.

MMn ist es ausreichend, wenn die Leute Ingame zu erkennen sind.

2024-04-20 23:09 UTC, motrellin commented
> Würde anregen die Helfer nicht in die Teamliste aufzunehmen. Wir wollten die ja explizit nicht als Teamler haben + ist es so weniger Wartungsaufwand für uns, wenn da Personen auf dem Posten variieren.
> 
> MMn ist es ausreichend, wenn die Leute Ingame zu erkennen sind.

Ich denke, die Übersicht ist schön. Wir haben jetzt ja zwei Listen:
- Auf der Teamseite Team + Support
- Auf der Supportseite Support + Helfer.

Helfer werden also definitiv **nicht** als Teil des Teams dargestellt und @Ru8ior und ich haben darauf geachtet, dass auf der Supportseite ein visueller Unterschied zum Support sichtbar ist.

Bzgl. Wartungsaufwand: Der ist relativ gering, sehe ich also nicht als wirklichen Punkt. Und wenn doch, können wir das ja als Motivation sehen, weniger Fluktuation auf dem Posten zu haben :)

2024-04-21 16:46 UTC, RobZenFL approved these changes

2024-04-21 16:48 UTC, merged