Update support.md
FLBadoras/wiki pull request #111
Opened 2024-04-20 23:13 UTC by Ru8ior

---

### Related Issues

Closes #XXXX

### Reviewer's checklist

- [ ] ... Wurde eine gewisse Code-Qualität eingehalten?
- [ ] ... Stimmen die veränderten oder neu hinzugefügten Informationen?
- [ ] ... Wurden die Veränderungen getestet?

2024-04-21 00:03 UTC, motrellin requested changes

2024-04-21 00:03 UTC, motrellin commented on support.md
> +    aktiv deinen bisherigen Channel zu wechseln mithilfe des Befehl /h [Nachricht].
```suggestion
- Ingame kannst du den Befehl [`/h`](/commands/h) nutzen. Mehr Informationen
  hierzu findest du [hier](/systems/chat/#hilfe-chat).
```
Das spiegelt das wieder, was wir auf Discord besprochen haben, right @Ru8ior ?

2024-04-21 00:03 UTC, motrellin commented on support.md
> +- Auf unserem Discord findest du den Channel "#supportticket" im Bereich support.
```suggestion
- Auf unserem Discord findest du den Channel "#supportticket" im Bereich Support. 
```

2024-04-21 16:45 UTC, RobZenFL submitted a review, later dismissed

2024-04-22 16:28 UTC, motrellin approved these changes

2024-04-22 16:29 UTC, merged