Neuer Command: marry.md
FLBadoras/wiki pull request #129
Opened 2024-05-04 16:16 UTC by DerSpieler13

Ein Command, um andere Spieler zu heiraten.

---

### Related Issues

Closes #XXXX

### Reviewer's checklist

- [ ] ... Wurde eine gewisse Code-Qualität eingehalten?
- [ ] ... Stimmen die veränderten oder neu hinzugefügten Informationen?
- [ ] ... Wurden die Veränderungen getestet?

2024-05-04 17:19 UTC, motrellin requested changes
Danke schonmal!

War btw verwundert, dass es zu `/marry` selbst keine Issue gab. 😅

2024-05-04 17:19 UTC, motrellin commented on _commands/marry.md
> +command: "/marry"
```suggestion
command: "/marry {Name}"
```
Ich bin mir gerade nicht sicher, aber gibt man nicht wahrscheinlich auch den Namen der Person an, die man heiratet?

2024-05-04 17:19 UTC, motrellin commented on _commands/marry.md
> +description: "Heirate deine/n Liebste/n"
```suggestion
description: "Heirate deine/n Liebste/n."
```
Punkt am Satzende

2024-05-04 17:19 UTC, motrellin commented on _commands/marry_hug.md
> +description: "Mit dem Command kann man seine(n) Partner(in) umarmen. Dafür darfst du maximal 2 Meter von der Person entfernt sein."
```suggestion
description: "Umarme deine(n) Partner(in). Dafür darfst du maximal 2 Meter von der Person entfernt sein."
```
Anpassung an den Sprachstil in der restlichen Liste.

2024-05-04 17:19 UTC, motrellin commented on _commands/marry_kiss.md
> +description: "Küsse deine(n) Partner(in). Dafür darfst du maximal 2 Meter von der Person entfernt sein. Alternativ kannst du die Person Rechtsklicken, während du Shift gedrückt hältst."
```suggestion
description: "Küsse deine(n) Partner(in). Dafür darfst du maximal 2 Meter von der Person entfernt sein. Alternativ kannst du die Person rechtsklicken, während du Shift gedrückt hältst."
```

2024-05-04 17:37 UTC, RobZenFL commented on _commands/marry.md
> +command: "/marry"
Hochzeiten werden durch Standesbeamte durchgeführt. Den Command könnt ihr also streichen.

2024-05-05 21:20 UTC, motrellin approved these changes
LGTM, danke!

2024-05-05 21:21 UTC, RobZenFL approved these changes

2024-05-05 21:24 UTC, merged