Pre-Commit: MD013
FLBadoras/wiki pull request #155
Opened 2024-05-11 11:32 UTC by motrellin

Activating MD013

---

### Related Issues

Closes #XXXX

### Reviewer's checklist

- [ ] ... Wurde eine gewisse Code-Qualität eingehalten?
- [ ] ... Stimmen die veränderten oder neu hinzugefügten Informationen?
- [ ] ... Wurden die Veränderungen getestet?

2024-05-11 11:33 UTC, motrellin commented
pre-commit.ci autofix

2024-05-16 16:06 UTC, RobZenFL requested changes

2024-05-16 16:06 UTC, RobZenFL commented on support.md
> +permanenter Ban wird natürlich _nicht_ entfernt, weil eine Verwarnung nach 4
Würde "Bann" immer deutsch nutzen

2024-05-16 16:13 UTC, motrellin commented on support.md
> +permanenter Ban wird natürlich _nicht_ entfernt, weil eine Verwarnung nach 4
Hab ich mal geändert. Kannste ja @Ru8ior nochmal sagen, falls er das hier nicht liest.

2024-05-16 16:14 UTC, RobZenFL submitted a review, later dismissed

2024-05-16 16:15 UTC, RobZenFL commented on support.md
> +permanenter Ban wird natürlich _nicht_ entfernt, weil eine Verwarnung nach 4
Der ist paar Tage weg

2024-05-16 18:11 UTC, motrellin commented on support.md
> +permanenter Ban wird natürlich _nicht_ entfernt, weil eine Verwarnung nach 4
Gut. Nachdem "Bann" in der Tat das deutsche Wort ist, nehmen wir das einfach. Falls das nicht gepasst hat @Ru8ior : Einfach nochmal melden.

2024-05-16 18:11 UTC, merged