Lists_listsoverhaul
FLBadoras/wiki pull request #186
Opened 2024-11-03 21:27 UTC by RobZenFL

- Bestehende Einträge ergänzt.
- Neue Listen und Systeme eingefügt.
- Ein weiterer Command ergänzt.
- Bestehendes Bild in Pixelgröße angepasst.

---

### Related Issues

Closes #XXXX

### Reviewer's checklist

- [ ] ... Wurde eine gewisse Code-Qualität eingehalten?
- [ ] ... Stimmen die veränderten oder neu hinzugefügten Informationen?
- [ ] ... Wurden die Veränderungen getestet?

2024-11-03 21:29 UTC, RobZenFL commented
Beim gefailten Check haben wir folgendes Problem: Markdown-Sprache wird in der Zeilenlänge nicht beachtet, heißt er schlägt an Punkten an, an denen eigentlich keine 80 Zeichen vorhanden sind. Ich finds aber doof, die auch runterzubrechen, weil dann einige Zeilen deutlich kürzer sind in einem Textblock, nur weil eine Verlinkung drin ist.

2024-11-11 12:43 UTC, motrellin requested changes

2024-11-11 12:43 UTC, motrellin commented on _lists/shops.md
> +_Tipp: Du findest die Standorte der Shops auch auf der [Livekarte](/commands/karte)._
```suggestion
_Tipp: Du findest die Standorte der Shops auch auf der [Livekarte](http://karte.badoras.life/)._
```
Wollen wir hier gleich auf die Karte verlinken?

2024-11-11 12:43 UTC, motrellin commented on _systems/dungeons.md
> +findest du in der Dungeonhöhle auf der Pirateninsel ([Karte](/commands/karte)).
```suggestion
findest du in der Dungeonhöhle auf der Pirateninsel ([Karte](http://karte.badoras.life/)).
```
Direkt Live-Karte?

2024-11-11 12:43 UTC, motrellin commented on _systems/dungeons.md
> +[Sammelobjekte](/lists/collectibles) und [Blueprints](/lists/blueprints) erwerben.
```suggestion
[Sammelobjekte](/lists/collectibles) und [Blueprints](/systems/blueprints) erwerben.
```
Falscher Link

2024-11-11 12:43 UTC, motrellin commented on _systems/dungeons.md
> +_Bosstruhen werden mit der Teilnehmerzahl skaliert._
Ich würde empfehlen, das ihr das hier nochmal umformuliert. Zum einen kommt die Frage auf, wie skaliert wird (gibt es mehr Gewinne, wenn mehr Personen teilnehmen? Deutlich mehr, sodass sich Teamwork lohnt? Deutlich weniger, weil es im Team einfacher ist?)

Zum Anderen gibt es sicherlich leichtere Sprache zu "skaliert", die mehr Personen direkt verstehen.

2024-11-11 12:43 UTC, motrellin commented on _systems/furnituremanufacturer.md
> +title: Fabrik
```suggestion
short_name: furnituremanufacturer
title: Möbelmanufaktur
```

2024-11-11 12:43 UTC, motrellin commented on _systems/factory.md
> +verarbeiten. Im Durchschnitt erhältst du von ihm 9 Euro pro Kassiteritblock,
```suggestion
Du kannst bei ihm auch Kassiterit aus der [Mine](/jobs/mine) verkaufen. Dafür musst du allerdings
das Kassiterit vorher in einer Werkbank zu Kassiteritblöcken
verarbeiten. Im Durchschnitt erhältst du von ihm 9 Euro pro Kassiteritblock,
```
Sprachliche Verbesserung

2024-11-11 12:43 UTC, motrellin commented on _systems/factory.md
> +_Zeitpunkt zu verkaufen, sofern du nicht auf das schnelle Geld angewiesen bist._
```suggestion
Es lohnt sich also, die Preise im Blick zu behalten und zum richtigen
Zeitpunkt zu verkaufen, sofern du nicht auf das schnelle Geld angewiesen bist.
```
Über dieses Tipp stolpert man beim Lesen, weil der Satz danach wieder sprachlich an den vorangehenden Satz anschließt.

2024-11-11 12:43 UTC, motrellin commented on _systems/furnituremanufacturer.md
Eventuell wäre es eine Idee, diesen Beitrag in den zur Fabrik als Unterpunkt einzugliedern.

2024-11-11 12:43 UTC, motrellin commented on _systems/school.md
> +{% include lists_table.md %}
```suggestion
---
# {{ page.title }}

Im Schulungszentrum gibt es vier verschiedene Kategorien an durchführbaren
Schulungen: Jobs, Fabrik, Möbelmanufaktur und Sonstiges. Geh einfach zu den
Tafeln im ersten Obergeschoss und klicke sie an.

Bei der Mitarbeiterin im unteren Raum hast du einen Überblick über deine
freigeschalteten Perks und vorhandenen Wissenspunkte.

## Ablauf

Jede Schulung benötigt neben Wissenspunkten eine gewisse Menge an Material,
die man mitbringen muss. Sie dauert 8 Stunden und schaltet gewisse Perks oder
andere Dinge (Möbel, Wassertankgröße, ...) frei. Die meisten Schulungen haben
verdeckte Stufen, man schaltet also die nächsthohe Stufe der Schulung erst frei,
wenn man die aktuelle erlernt hat.

_Tipp: Hier kannst du auch weitere Kategorien der [Möbelmanufaktur](/systems/furnituremanufacturer) freischalten._

## Wissenspunkte

Wissenspunkt erhältst du durch das Nutzen von Wissensbüchern. Diese kannst du
entweder finden/erhalten oder dir selbst herstellen. Dafür benötigst du
Wissensfragmente. Es gibt hier drei verschiedene Rezepte, die du herausfinden
kannst, um dir Wissensbücher herzustellen.

Hier findest du Wissensfragmente und -bücher:
- Dungeons
- Farmwelttruhen
- Jobs (Mine, Plantagen)
- Kiosk
- Korallentauchen
- Schrottplatz
```

2024-11-11 13:14 UTC, RobZenFL commented on _lists/blueprints.md
Ja, ich habe die Datei in SYSTEMS verschoben und zu einer Erklärbärdatei gemacht :D

2024-11-11 13:20 UTC, RobZenFL commented on _systems/furnituremanufacturer.md
Gebe ich dir Recht. Frage ist eben, ob das als einzelner Punkt noch offensichtlicher auf die Möglichkeit hinweist, sich selbst Möbel zu bauen. Im Fabrik-Eintrag ist auf jeden Fall hier rüber verlinkt.

2024-11-11 17:37 UTC, motrellin approved these changes

2024-11-11 17:37 UTC, motrellin commented on _systems/dungeons.md
> +_in die Arbeit reinteilen. Somit lohnt es sich hier, im Team zu arbeiten._
Sehr schön!

2024-11-11 17:37 UTC, motrellin commented on _systems/furnituremanufacturer.md
Dann lassen wir es erstmal so, wie es jetzt ist.

2024-11-11 17:45 UTC, motrellin approved these changes
war ja nur das Zeilenlängen-Zeugs

2024-11-11 17:45 UTC, merged