Verbesserungen-1124
FLBadoras/wiki pull request #191
Opened 2024-11-25 23:30 UTC by RobZenFL

Neue Punkte ergänzt, bestehende Dinge abgeändert. Real Magic happened hier!

Somit sind die Arbeiten an den Systemen vorerst abgeschlossen, bis sich was ändert oder neue Dinge hinzukommen (oder fehlende Sachen auffallen).

Aktuell offen: Blueprint-Liste (aka Mammut-Projekt)

---

### Related Issues

Closes #XXXX

### Reviewer's checklist

- [ ] ... Wurde eine gewisse Code-Qualität eingehalten?
- [ ] ... Stimmen die veränderten oder neu hinzugefügten Informationen?
- [ ] ... Wurden die Veränderungen getestet?

2024-12-08 19:39 UTC, motrellin requested changes

2024-12-08 19:39 UTC, motrellin commented on _maps/badoras.md
> +Zur Rennstrecke gibt es während eines vom [Serverteam](/team_members) veranstalteten Renn-Events
```suggestion
Zur Rennstrecke gibt es während eines vom [Serverteam](/team) veranstalteten Renn-Events
```
Falscher Link

2024-12-08 19:54 UTC, RobZenFL commented on _commands/xp.md
> +description: "Fülle deine Erfahrungspunkte in Erfahrungsflaschen ab. Ohne optionales Argument ausgeführt, zeigt der Befehl deine aktuellen Erfahrungspunkte an."
Jap, geht ums optische. Sieht so halt immernoch massiv aus :D Dachte deswegen, dass weniger Infos durchaus ausreichen.

2024-12-08 21:27 UTC, motrellin commented on _commands/xp.md
> +description: "Fülle deine Erfahrungspunkte in Erfahrungsflaschen ab. Ohne optionales Argument ausgeführt, zeigt der Befehl deine aktuellen Erfahrungspunkte an."
Wie findest du die Screenshot-Version?

2024-12-08 21:56 UTC, RobZenFL commented on _commands/xp.md
> +description: "Fülle deine Erfahrungspunkte in Erfahrungsflaschen ab. Ohne optionales Argument ausgeführt, zeigt der Befehl deine aktuellen Erfahrungspunkte an."
Immernoch massiv. Weil die Zeile halt so eng ist. Aber man könnte es auch so lassen, immerhin liest sichs jetzt besser.

2024-12-09 10:50 UTC, motrellin commented on _commands/xp.md
> +description: "Fülle deine Erfahrungspunkte in Erfahrungsflaschen ab. Ohne optionales Argument ausgeführt, zeigt der Befehl deine aktuellen Erfahrungspunkte an."
Ich bin auch eher dafür, den Text da zu lassen, weil der Befehl sonst schwierig zu verstehen sein könnte, zumindest in seiner Gänze.

2024-12-09 10:57 UTC, motrellin approved these changes

2024-12-09 19:51 UTC, merged