Create webseite.md
FLBadoras/wiki pull request #82
Opened 2024-04-02 16:37 UTC by Ru8ior

Closes #42

---

### Related Issues

Closes #XXXX

### Reviewer's checklist

- [ ] ... Wurde eine gewisse Code-Qualität eingehalten?
- [ ] ... Stimmen die veränderten oder neu hinzugefügten Informationen?
- [ ] ... Wurden die Veränderungen getestet?

2024-04-02 16:54 UTC, motrellin requested changes
@RobZenFL am besten schaust du da auch nochmal drauf.

2024-04-02 16:54 UTC, motrellin commented on _commands/webseite.md
> +command: "/webseite"
```suggestion
command: "/website"
```

Ich würde als Hauptcommand eher die englische Version lassen. Ist zumindest in meinem Sprachgebrauch das üblichere. (Bei dir vermutlich auch, wenn ich die Command-Beschreibung anschaue ^^).

2024-04-02 16:54 UTC, motrellin commented on _commands/webseite.md
> +aliases: ["/homepage"]
```suggestion
aliases: ["/webseite","/homepage"]
```

Bei dem Befehl müssten ja alle 3 funktionieren.

2024-04-04 21:55 UTC, RobZenFL submitted a review, later dismissed

2024-04-05 11:43 UTC, RobZenFL approved these changes

2024-04-05 20:32 UTC, motrellin commented
Auf den Review für Datei-Umbenennung wegen Einheitlichkeit verzichte ich jetzt mal.

2024-04-05 20:33 UTC, merged