Support
FLBadoras/wiki pull request #95
Opened 2024-04-09 22:09 UTC by motrellin

See commit messages.
---

### Related Issues

Closes #XXXX

### Reviewer's checklist

- [ ] ... Wurde eine gewisse Code-Qualität eingehalten?
- [ ] ... Stimmen die veränderten oder neu hinzugefügten Informationen?
- [ ] ... Wurden die Veränderungen getestet?

2024-04-09 22:10 UTC, RobZenFL approved these changes

2024-04-12 19:50 UTC, Ru8ior requested changes

2024-04-12 19:50 UTC, Ru8ior commented on support.md
> +Stelle.
```suggestion
`/hilfe`? Kein Problem, dafür steht dir unser kompetentes Support-Team gerne zur
Seite.
```
Finde ich persönlich eine besser Formulierung (einfacher?)

2024-04-12 19:53 UTC, Ru8ior approved these changes

2024-04-12 19:55 UTC, motrellin commented
Notiz an mich: Wenn gemerged, Issues zu Punktesystem und Helfer erstellen.

2024-04-17 19:21 UTC, motrellin commented
Seit dem letzten Review von @RobZenFL wurde nur Grammatik angepasst, ich merge das jetzt.

2024-04-17 19:21 UTC, merged